local c_gs = {
    Hero = "c_gs.Hero",
    S2C_HeroList = "c_gs.S2C_HeroList",
    C2S_UpgradeHeroLevReq = "c_gs.C2S_UpgradeHeroLevReq",
    S2C_UpgradeHeroLevRsp = "c_gs.S2C_UpgradeHeroLevRsp",
    C2S_UpgradeHeroStarReq = "c_gs.C2S_UpgradeHeroStarReq",
    S2C_UpgradeHeroStarRsp = "c_gs.S2C_UpgradeHeroStarRsp",
    C2S_Login = "c_gs.C2S_Login",
    S2C_Login = "c_gs.S2C_Login",
    C2S_CreateCharacter = "c_gs.C2S_CreateCharacter",
    S2C_CreateCharacter = "c_gs.S2C_CreateCharacter",
    S2C_Disconnect = "c_gs.S2C_Disconnect",
    S2C_LoginFinish = "c_gs.S2C_LoginFinish",
    S2C_PlayerData = "c_gs.S2C_PlayerData",
    S2C_PropertyList = "c_gs.S2C_PropertyList",
    S2C_BigPropertyList = "c_gs.S2C_BigPropertyList",
    S2C_PlayerSettings = "c_gs.S2C_PlayerSettings",
    S2C_VipData = "c_gs.S2C_VipData",
    S2C_SyncVipLevExp = "c_gs.S2C_SyncVipLevExp",
    BigIntSimilar = "c_gs.BigIntSimilar",
    PlayerBrief = "c_gs.PlayerBrief",
    PlayerDetail = "c_gs.PlayerDetail",
    Property = "c_gs.Property",
    BigProperty = "c_gs.BigProperty",
}
 return c_gs